/*
 * This source file was generated by the Gradle 'init' task
 */
package javaprojects;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

import java.io.IOException;

import okhttp3.Headers;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void HTTPRequest(OkHttpClient client) throws IOException {

        Request request = new Request.Builder()
                .url("https://raw.githubusercontent.com/robiningelbrecht/wca-rest-api/master/api/persons/2021LIUD02.json")
                .build();

        try (Response response = client.newCall(request).execute()) {
            if (!response.isSuccessful())
                throw new IOException("Unexpected Code" + response);

            Headers responseHeaders = response.headers();
            for (int i = 0; i < responseHeaders.size(); i++) {
                // System.out.println(responseHeaders.name(i) + ": " +
                // responseHeaders.value(i));
            }

            System.out.println(response.body().string());
        } catch (IOException err) {
            System.out.println("Error Occured: " + err.getMessage());
        }

    }

    public static void main(String[] args) throws IOException {
        final OkHttpClient client = new OkHttpClient();
        HTTPRequest(client);
        System.out.println("FINISHED");
    }
}
