/*
 * This source file was generated by the Gradle 'init' task
 */
package CubeTracker;

import java.io.IOException;
import java.util.Scanner;

import CubeTracker.api.WcaClient;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        WcaClient client = new WcaClient();
        // Scanner myObj = new Scanner(System.in);
        // System.out.println("Enter WCA ID for competitor information:");
        // String wcaID = myObj.nextLine();
        // client.personData(wcaID);
        // myObj.close();
        client.listContinents();
    }
}
